spring:
  application:
    name: cires-users-generator

  jpa:
    hibernate:
      ddl-auto: create-drop

  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver

logging:
  level:
    org:
      springframework:
        web: INFO

server:
  port: 9090

springdoc:
  api-docs:
    path: /api-docs

jwt:
  secret:
    key: 78214125442A472D4A614E645267556B58703273357638792F423F4528482B4D
  expiration:
    time: 86400000