spring:
  application:
    name: cires-users-generator

  jpa:
    hibernate:
      ddl-auto: create-drop

  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver

logging:
  level:
    org:
      springframework:
        web: DEBUG

server:
  port: 9090